name: gallery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  image_picker: ^1.0.4
  lottie: ^2.6.0
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/splash_screen_animation.json
    - assets/animations/authSuccessAnimation.json
    - assets/animations/authErrorAnimation.json
    - assets/images/
  
  fonts:
    - family: InstaSans
      fonts:
      - asset: assets/fonts/instagram-sans-font/Instagram Sans Headline.otf